/* GENERATED by tools/convert.py - do not edit. */
const char *fte_layer_matmul_name(int L, int w) {
  static const char *T[12][3] = {
    {"onnx::MatMul_1536", "onnx::MatMul_1537", "onnx::MatMul_1538"},
    {"onnx::MatMul_1549", "onnx::MatMul_1550", "onnx::MatMul_1551"},
    {"onnx::MatMul_1562", "onnx::MatMul_1563", "onnx::MatMul_1564"},
    {"onnx::MatMul_1575", "onnx::MatMul_1576", "onnx::MatMul_1577"},
    {"onnx::MatMul_1588", "onnx::MatMul_1589", "onnx::MatMul_1590"},
    {"onnx::MatMul_1601", "onnx::MatMul_1602", "onnx::MatMul_1603"},
    {"onnx::MatMul_1614", "onnx::MatMul_1615", "onnx::MatMul_1616"},
    {"onnx::MatMul_1627", "onnx::MatMul_1628", "onnx::MatMul_1629"},
    {"onnx::MatMul_1640", "onnx::MatMul_1641", "onnx::MatMul_1642"},
    {"onnx::MatMul_1653", "onnx::MatMul_1654", "onnx::MatMul_1655"},
    {"onnx::MatMul_1666", "onnx::MatMul_1667", "onnx::MatMul_1668"},
    {"onnx::MatMul_1679", "onnx::MatMul_1680", "onnx::MatMul_1681"},
  };
  return T[L][w];
}
