#!/usr/bin/env python3
"""Offline (dev-only): convert the upstream ONNX model -> model.fte and dump golden test data.

The shipped runtime is pure C with zero dependencies; this regeneration tool may use any
library. It:
  1. locates the cached upstream ONNX model,
  2. stores each fp16 weight in a flat mmap-able model.fte,
  3. copies the tokenizer vocab to vocab.tsv,
  4. emits src/layer_matmul_names.c (per-layer MatMul weight names, in graph order),
  5. dumps golden reference vectors (from the ONNX Runtime reference) + token ids for tests.
"""
import glob
import json
import os
import struct
import sys

import numpy as np
import onnx
from onnx import numpy_helper

ALIGN, NAME_MAX, MAGIC, VERSION = 64, 64, 0x31455446, 2

# C-layout-matching packers (see src/fte_format.h)
HDR = struct.Struct("<QQ" + "I" * 11)          # table_off, blob_off, then 11 uint32
ENT = struct.Struct(f"<QQ{NAME_MAX}s" + "i" * 6)  # offset, nbytes, name, ndim, shape[4], _pad


def find_model_dir():
    from fastembed.common.utils import define_cache_dir
    base = str(define_cache_dir())
    hits = glob.glob(os.path.join(base, "**", "model_optimized.onnx"), recursive=True)
    if not hits:
        sys.exit("model_optimized.onnx not found; run TextEmbedding('BAAI/bge-small-en-v1.5') first")
    return os.path.dirname(hits[0])


FTE_DT_F32, FTE_DT_F16 = 0, 1


def write_fte(inits, path):
    names = sorted(inits)
    blob, entries, off = bytearray(), [], 0
    for n in names:
        src = inits[n]
        # Big 2-D tensors (matmul weights + embedding tables) -> fp16 (matches the
        # shipped model, halves bandwidth). Tiny 1-D tensors (biases, LayerNorm) -> fp32.
        if src.ndim == 2:
            a = np.ascontiguousarray(src.astype(np.float16))
            dtype = FTE_DT_F16
        else:
            a = np.ascontiguousarray(src.astype(np.float32))
            dtype = FTE_DT_F32
        pad = (-off) % ALIGN
        blob += b"\x00" * pad
        off += pad
        entries.append((n, list(a.shape), off, a.nbytes, dtype))
        blob += a.tobytes()
        off += a.nbytes

    hdr_size = HDR.size
    table_off = (hdr_size + ALIGN - 1) // ALIGN * ALIGN
    table_size = ENT.size * len(entries)
    blob_off = (table_off + table_size + ALIGN - 1) // ALIGN * ALIGN

    with open(path, "wb") as f:
        f.write(HDR.pack(table_off, blob_off, MAGIC, VERSION,
                         384, 12, 12, 1536, 30522, 512, 2, len(entries), 0))
        f.write(b"\x00" * (table_off - hdr_size))
        for (name, shape, o, nb, dtype) in entries:
            sh = (shape + [0, 0, 0, 0])[:4]
            f.write(ENT.pack(blob_off + o, nb,
                             name.encode().ljust(NAME_MAX, b"\x00")[:NAME_MAX],
                             len(shape), sh[0], sh[1], sh[2], sh[3], dtype))
        f.write(b"\x00" * (blob_off - (table_off + table_size)))
        f.write(blob)
    print(f"wrote {path}: {len(entries)} tensors, blob {len(blob) / 1e6:.1f} MB")


def emit_matmul_names(g, path="src/layer_matmul_names.c"):
    mm = [n for n in g.node if n.op_type == "MatMul"]
    names = [n.input[1] for n in mm]  # input[1] is the weight initializer
    assert len(names) == 36, len(names)
    with open(path, "w") as f:
        f.write("/* GENERATED by tools/convert.py - do not edit. */\n")
        f.write("const char *fte_layer_matmul_name(int L, int w) {\n")
        f.write("  static const char *T[12][3] = {\n")
        for L in range(12):
            f.write('    {"%s", "%s", "%s"},\n' % (names[3 * L], names[3 * L + 1], names[3 * L + 2]))
        f.write("  };\n  return T[L][w];\n}\n")
    print("emitted", path, "(verify ordering via e2e test)")


def emit_vocab(model_dir):
    from tokenizers import Tokenizer
    tk = Tokenizer.from_file(os.path.join(model_dir, "tokenizer.json"))
    vocab = tk.get_vocab()
    with open("vocab.tsv", "w") as f:
        for tok, i in sorted(vocab.items(), key=lambda x: x[1]):
            f.write(f"{tok}\t{i}\n")
    print("emitted vocab.tsv", len(vocab), "tokens")
    return tk


GOLDEN_DOCS = [
    "hello world",
    "the weather is nice and warm today",
    "Machine learning turns text into numerical vectors.",
    "The quick brown fox jumps over the lazy dog.",
]


def dump_golden(out_dir, tk):
    from fastembed import TextEmbedding
    m = TextEmbedding(model_name="BAAI/bge-small-en-v1.5")
    vecs = np.array(list(m.embed(GOLDEN_DOCS)), dtype=np.float32)  # CLS + L2-normalized
    os.makedirs(out_dir, exist_ok=True)
    vecs.tofile(os.path.join(out_dir, "golden_vecs.f32"))
    with open(os.path.join(out_dir, "golden_meta.txt"), "w") as f:
        f.write(f"{len(GOLDEN_DOCS)} 384\n")
    with open(os.path.join(out_dir, "golden_docs.txt"), "w") as f:
        for d in GOLDEN_DOCS:
            f.write((d if d else "~") + "\n")
    rows = [{"text": d, "ids": tk.encode(d).ids} for d in GOLDEN_DOCS]
    with open(os.path.join(out_dir, "golden_tokens.json"), "w") as f:
        json.dump(rows, f)
    # easy-to-parse variant for the C test: "text<TAB>id1,id2,..."
    with open(os.path.join(out_dir, "golden_tokens.txt"), "w") as f:
        for r in rows:
            f.write(r["text"] + "\t" + ",".join(str(i) for i in r["ids"]) + "\n")
    print("dumped golden vectors", vecs.shape, "+ golden token ids")


if __name__ == "__main__":
    md = find_model_dir()
    g = onnx.load(os.path.join(md, "model_optimized.onnx")).graph
    inits = {i.name: numpy_helper.to_array(i) for i in g.initializer}
    write_fte(inits, "model.fte")
    emit_matmul_names(g)
    tk = emit_vocab(md)
    dump_golden("tests/data", tk)
